name: fast-api
on:
  push:
    branches: ["master", "main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["master", "main"]

env:
  REGISTRY: "" # 如果为空，则使用 DockerHUb

jobs:
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      - name: "拉取仓库代码"
        uses: actions/checkout@v4
      - name: "登录 Docker Hub "
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "构建镜像"
        run: |
          pwd && ls
          cd fast-api
          pwd && ls
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fast-api --no-cache --force-rm .
      - name: "推送镜像"
        run: |
          pwd && ls
          docker push ${{ secrets.DOCKER_USERNAME }}/fast-api
