name: jdk7-jvm
on:
  push:
    branches: ["master", "main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["master", "main"]

env:
  REGISTRY: "" # å¦‚æœä¸ºç©ºï¼Œåˆ™ä½¿ç”¨ DockerHUb

jobs:
  build:
    # è¿è¡Œç¯å¢ƒ
    runs-on: ubuntu-latest
    # æ­¥éª¤
    steps:
      - name: "ğŸ“¥ æ‹‰å–ä»“åº“ä»£ç "
        uses: actions/checkout@v4
      - name: "ğŸ” ç™»å½• Docker Hub "
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "ğŸ—ï¸ æ„å»ºé•œåƒ"
        run: |
          pwd && ls
          cd jdk7
          pwd && ls
          docker build -t ${{ secrets.DOCKER_USERNAME }}/jdk7-jvm --no-cache --force-rm .
      - name: "ğŸš€ æ¨é€é•œåƒ"
        run: |
          pwd && ls
          docker push ${{ secrets.DOCKER_USERNAME }}/jdk7-jvm
